name: Pylint

on:
  push:
    paths-ignore:
      - 'examples/*'
      - '*.md'
      - 'setup.py'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install pandas
        pip install vobject
    - name: Analysing the code with pylint
      run: |
        python -m pylint --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` |
        tee pylint.txt
